version: '3'
services:
  bank-api:
    container_name: bank-api
    build: .
    command: bash -c "rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    links:
      - postgres
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=bank_api
